# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentData',
            fields=[
                ('anime_url', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, default='', null=True)),
                ('synopsis', models.TextField(blank=True, default='', null=True)),
                ('english_name', models.TextField(blank=True, default='', null=True)),
                ('synonyms', models.TextField(blank=True, default='', null=True)),
                ('japanese_name', models.TextField(blank=True, default='', null=True)),
                ('media', models.TextField(blank=True, default='', null=True)),
                ('episodes', models.TextField(blank=True, default='', null=True)),
                ('aired', models.TextField(blank=True, default='', null=True)),
                ('broadcast', models.TextField(blank=True, default='', null=True)),
                ('licensors', models.TextField(blank=True, default='', null=True)),
                ('studios', models.TextField(blank=True, default='', null=True)),
                ('source', models.TextField(blank=True, default='', null=True)),
                ('genres', models.TextField(blank=True, default='', null=True)),
                ('duration', models.TextField(blank=True, default='', null=True)),
                ('rating', models.TextField(blank=True, default='', null=True)),
                ('score', models.TextField(blank=True, default='', null=True)),
                ('ranked', models.TextField(blank=True, default='', null=True)),
                ('members', models.TextField(blank=True, default='', null=True)),
                ('popularity', models.TextField(blank=True, default='', null=True)),
                ('favourites', models.TextField(blank=True, default='', null=True)),
                ('adaptation', models.TextField(blank=True, default='', null=True)),
                ('alternative_version', models.TextField(blank=True, default='', null=True)),
                ('side_story', models.TextField(blank=True, default='', null=True)),
                ('spinoff', models.TextField(blank=True, default='', null=True)),
                ('prequel', models.TextField(blank=True, default='', null=True)),
                ('sequel', models.TextField(blank=True, default='', null=True)),
                ('summary', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'content_data',
            },
        ),
    ]
