# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stride_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicStatistics',
            fields=[
                ('show_code', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('var', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('rating_zero', models.IntegerField(blank=True, null=True)),
                ('rating_one', models.IntegerField(blank=True, null=True)),
                ('rating_two', models.IntegerField(blank=True, null=True)),
                ('rating_three', models.IntegerField(blank=True, null=True)),
                ('rating_four', models.IntegerField(blank=True, null=True)),
                ('rating_five', models.IntegerField(blank=True, null=True)),
                ('rating_six', models.IntegerField(blank=True, null=True)),
                ('rating_seven', models.IntegerField(blank=True, null=True)),
                ('rating_eight', models.IntegerField(blank=True, null=True)),
                ('rating_nine', models.IntegerField(blank=True, null=True)),
                ('rating_ten', models.IntegerField(blank=True, null=True)),
                ('extra_1', models.IntegerField(blank=True, null=True)),
                ('extra_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'basic_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemRecs',
            fields=[
                ('show_code', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('rec_1', models.IntegerField(blank=True, null=True)),
                ('rec_2', models.IntegerField(blank=True, null=True)),
                ('rec_3', models.IntegerField(blank=True, null=True)),
                ('rec_4', models.IntegerField(blank=True, null=True)),
                ('rec_5', models.IntegerField(blank=True, null=True)),
                ('rec_6', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_recs',
                'managed': False,
            },
        ),
    ]
